# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: FrontendBuild
        displayName: Build Frontend React
        pool:
          name: 'Skyline'
          demands:
          - agent.name -equals LAPTOP-CJGFCSTM

        steps:
          - script:
              cd "D:\SkyLine\web"
              npm install
              npm run build
            displayName: 'Build Frontend'
      - job: BackendBuild
        displayName: Build Backend Spring Boot
        pool:
          name: 'Skyline'
          demands:
          - agent.name -equals LAPTOP-CJGFCSTM

        steps:       
          - script: 
              cd "D:\SkyLine\backend"
              mvn clean package -DskipTests
            displayName: 'Build Backend'
      
        
  - stage: Test
    displayName: Test Stage
    jobs:
      - job: FrontendTests
        displayName: Run Frontend Tests
        pool:
          name: 'Skyline'
          demands:
          - agent.name -equals LAPTOP-CJGFCSTM
        steps:    
          - script:
              cd "D:\SkyLine\web"
              npm install
              npm run test
            displayName: 'Run Frontend Tests'
      - job: BackendTests
        displayName: Run Backend Tests
        pool:
          name: 'Skyline'
          demands:
          - agent.name -equals LAPTOP-CJGFCSTM
        steps:     
          - script:
              cd "D:\SkyLine\backend"
              mvn clean test
            displayName: 'Run Backend Tests'
      
  - stage: Deploy
    displayName: Deploy Stage
    jobs:
      - job: DeployBackend
        displayName: Deploy Backend to Production
        pool:
          name: 'Skyline'
          demands:
          - agent.name -equals LAPTOP-CJGFCSTM
        steps:
          - script: 
              cd "D:\SkyLine\backend"
              mvn clean package -DskipTests
      - job: DeployFrontend
        displayName: Deploy Frontend to Production 
        pool: 
          name: 'Skyline'
          demands:
          - agent.name -equals LAPTOP-CJGFCSTM
        steps:
          - script: 
              cd "D:\SkyLine\web"
              npm install
              npm run build
