# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Skyline'
  demands:
  - agent.name -equals LAPTOP-CJGFCSTM

steps:
- checkout: self

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21.x'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: 'D:\Program Files\JAVA\jdk-21'
    jdkDestinationDirectory: 'backend'
    cleanDestinationDirectory: false
    createExtractDirectory: false
  displayName: 'Install JDK'

- script: |
    ./mvnw clean install
  displayName: 'Build Application'
  workingDirectory: 'backend'

- script: |
    ./mvnw test
  displayName: 'Run Tests'
  workingDirectory: 'backend'

- script: |
    ./mvnw spring-boot:run
  displayName: 'Start Application'
  workingDirectory: 'backend'