trigger:
- main

pool:
  name: 'Skyline'
  demands:
  - agent.name -equals LAPTOP-CJGFCSTM

steps:
- checkout: self

- script: |
    ./mvnw clean install
  displayName: 'Build Application'
  workingDirectory: 'backend'

- script: |
    ./mvnw test
  displayName: 'Run Tests'
  workingDirectory: 'backend'

- script: |
    docker run -p 8080:8080 backend_image
  displayName: 'Deploy Application'
  workingDirectory: 'backend'
  