services:
  backend-app:
    image: backend_image
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
    networks:
      - react-spring
      - spring-mysql
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=skyline
      - MYSQL_ROOT_PASSWORD=skyline
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","127.0.0.1","--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - my-db-volume:/var/lib/mysql
    networks:
      - spring-mysql
    
  frontend:
    image: frontend_image
    ports:
      - 3000:3000
    networks:
      - react-spring
    depends_on:
      - backend-app
    expose:
      - 3306
      - 33060


volumes:
  my-db-volume: {}

networks:
  react-spring: {}
  spring-mysql: {}