services:
  frontend:
    image: frontend_image
    ports:
      - 3000:3000
    networks:
      - react-spring

  backend-app:
    image: backend_image
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
    networks:
      - react-spring
      - spring-mysql
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=skyline
      - MYSQL_ROOT_PASSWORD=skyline
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p skyline"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - my-db-volume:/var/lib/mysql
    networks:
      - spring-mysql

volumes:
  my-db-volume:

networks:
  react-spring: {}
  spring-mysql: {}
  